"""changed weapon masteries model

Revision ID: 079967f435d0
Revises: d8c63bffff43
Create Date: 2024-07-29 14:21:54.745553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "079967f435d0"
down_revision: Union[str, None] = "d8c63bffff43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "character_skill_masteries_skill_id_key",
        "character_skill_masteries",
        type_="unique",
    )
    op.add_column(
        "character_weapon_masteries",
        sa.Column("weapon_group_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "character_weapon_masteries_weapon_id_key",
        "character_weapon_masteries",
        type_="unique",
    )
    op.drop_constraint(
        "idx_unique_character_weapon_masteries",
        "character_weapon_masteries",
        type_="unique",
    )
    op.create_unique_constraint(
        "idx_unique_character_weapon_masteries",
        "character_weapon_masteries",
        ["character_id", "weapon_group_id"],
    )
    op.drop_constraint(
        "character_weapon_masteries_weapon_id_fkey",
        "character_weapon_masteries",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "character_weapon_masteries",
        "weapon_groups",
        ["weapon_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("character_weapon_masteries", "weapon_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "character_weapon_masteries",
        sa.Column("weapon_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "character_weapon_masteries", type_="foreignkey")
    op.create_foreign_key(
        "character_weapon_masteries_weapon_id_fkey",
        "character_weapon_masteries",
        "weapons",
        ["weapon_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "idx_unique_character_weapon_masteries",
        "character_weapon_masteries",
        type_="unique",
    )
    op.create_unique_constraint(
        "idx_unique_character_weapon_masteries",
        "character_weapon_masteries",
        ["character_id", "weapon_id"],
    )
    op.create_unique_constraint(
        "character_weapon_masteries_weapon_id_key",
        "character_weapon_masteries",
        ["weapon_id"],
    )
    op.drop_column("character_weapon_masteries", "weapon_group_id")
    op.create_unique_constraint(
        "character_skill_masteries_skill_id_key",
        "character_skill_masteries",
        ["skill_id"],
    )
    # ### end Alembic commands ###
