"""updated character models

Revision ID: 161dab0c6804
Revises: 49db8c33b18f
Create Date: 2024-06-28 13:51:34.327883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "161dab0c6804"
down_revision: Union[str, None] = "49db8c33b18f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_currencies",
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["currency_id"], ["currencies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "currency_id", name="idx_unique_character_currencies"
        ),
    )
    op.create_unique_constraint(
        "idx_unique_character_skill_masteries",
        "character_skill_masteries",
        ["character_id", "skill_id"],
    )
    op.create_unique_constraint(
        "idx_unique_character_weapon_masteries",
        "character_weapon_masteries",
        ["character_id", "weapon_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "idx_unique_character_weapon_masteries",
        "character_weapon_masteries",
        type_="unique",
    )
    op.drop_constraint(
        "idx_unique_character_skill_masteries",
        "character_skill_masteries",
        type_="unique",
    )
    op.drop_table("character_currencies")
    # ### end Alembic commands ###
