"""test delete

Revision ID: 177803f23de6
Revises: f56fdb6f953a
Create Date: 2024-06-26 17:49:31.356153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "177803f23de6"
down_revision: Union[str, None] = "f56fdb6f953a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "armor_trait_association_armor_id_fkey",
        "armor_trait_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "armor_trait_association_armor_trait_id_fkey",
        "armor_trait_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "armor_trait_association",
        "armor_traits",
        ["armor_trait_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "armor_trait_association",
        "armors",
        ["armor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("feat_trait_feat_id_fkey", "feat_trait", type_="foreignkey")
    op.drop_constraint("feat_trait_trait_id_fkey", "feat_trait", type_="foreignkey")
    op.create_foreign_key(
        None, "feat_trait", "feats", ["feat_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "feat_trait", "feat_traits", ["trait_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("god_domain_god_id_fkey", "god_domain", type_="foreignkey")
    op.drop_constraint("god_domain_domain_id_fkey", "god_domain", type_="foreignkey")
    op.create_foreign_key(
        None, "god_domain", "gods", ["god_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "god_domain", "domains", ["domain_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "god_domain", type_="foreignkey")
    op.drop_constraint(None, "god_domain", type_="foreignkey")
    op.create_foreign_key(
        "god_domain_domain_id_fkey", "god_domain", "domains", ["domain_id"], ["id"]
    )
    op.create_foreign_key(
        "god_domain_god_id_fkey", "god_domain", "gods", ["god_id"], ["id"]
    )
    op.drop_constraint(None, "feat_trait", type_="foreignkey")
    op.drop_constraint(None, "feat_trait", type_="foreignkey")
    op.create_foreign_key(
        "feat_trait_trait_id_fkey", "feat_trait", "feat_traits", ["trait_id"], ["id"]
    )
    op.create_foreign_key(
        "feat_trait_feat_id_fkey", "feat_trait", "feats", ["feat_id"], ["id"]
    )
    op.drop_constraint(None, "armor_trait_association", type_="foreignkey")
    op.drop_constraint(None, "armor_trait_association", type_="foreignkey")
    op.create_foreign_key(
        "armor_trait_association_armor_trait_id_fkey",
        "armor_trait_association",
        "armor_traits",
        ["armor_trait_id"],
        ["id"],
    )
    op.create_foreign_key(
        "armor_trait_association_armor_id_fkey",
        "armor_trait_association",
        "armors",
        ["armor_id"],
        ["id"],
    )
    # ### end Alembic commands ###
