"""updated character models

Revision ID: 18914faf0a1f
Revises: fd0e27e48002
Create Date: 2024-06-28 15:52:58.206834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18914faf0a1f"
down_revision: Union[str, None] = "fd0e27e48002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_currencies")
    op.drop_table("character_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_items",
        sa.Column("quantity", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("character_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name="character_items_character_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name="character_items_item_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="character_items_pkey"),
        sa.UniqueConstraint(
            "character_id", "item_id", name="idx_unique_character_items"
        ),
    )
    op.create_table(
        "character_currencies",
        sa.Column("quantity", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("character_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("currency_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name="character_currencies_character_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name="character_currencies_currency_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="character_currencies_pkey"),
        sa.UniqueConstraint(
            "character_id", "currency_id", name="idx_unique_character_currencies"
        ),
    )
    # ### end Alembic commands ###
