"""added character stats model

Revision ID: 1b26b5589447
Revises: c44a9d1dc700
Create Date: 2024-06-28 13:06:03.372453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b26b5589447"
down_revision: Union[str, None] = "c44a9d1dc700"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_stats",
        sa.Column("strength", sa.SmallInteger(), nullable=False),
        sa.Column("dexterity", sa.SmallInteger(), nullable=False),
        sa.Column("constitution", sa.SmallInteger(), nullable=False),
        sa.Column("intelligence", sa.SmallInteger(), nullable=False),
        sa.Column("wisdom", sa.SmallInteger(), nullable=False),
        sa.Column("charisma", sa.SmallInteger(), nullable=False),
        sa.Column("max_speed", sa.SmallInteger(), nullable=False),
        sa.Column("speed", sa.SmallInteger(), nullable=False),
        sa.Column(
            "perception_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "unarmed_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "light_armor_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "medium_armor_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "heavy_armor_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "fortitude_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "reflex_armor_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "will_armor_mastery",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_stats")
    # ### end Alembic commands ###
