"""added name to description models

Revision ID: 24adcad1cdc7
Revises: bc75c9e444fc
Create Date: 2024-06-18 11:41:30.774162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24adcad1cdc7"
down_revision: Union[str, None] = "bc75c9e444fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feattraits", sa.Column("name", sa.String(length=500), nullable=False))
    op.create_index(op.f("ix_feattraits_name"), "feattraits", ["name"], unique=True)
    op.add_column("skillss", sa.Column("name", sa.String(length=500), nullable=False))
    op.create_index(op.f("ix_skillss_name"), "skillss", ["name"], unique=True)
    op.add_column(
        "spellcomponents", sa.Column("name", sa.String(length=500), nullable=False)
    )
    op.create_index(
        op.f("ix_spellcomponents_name"), "spellcomponents", ["name"], unique=True
    )
    op.add_column(
        "spellschools", sa.Column("name", sa.String(length=500), nullable=False)
    )
    op.create_index(op.f("ix_spellschools_name"), "spellschools", ["name"], unique=True)
    op.add_column(
        "spelltraditions", sa.Column("name", sa.String(length=500), nullable=False)
    )
    op.create_index(
        op.f("ix_spelltraditions_name"), "spelltraditions", ["name"], unique=True
    )
    op.add_column(
        "spelltraits", sa.Column("name", sa.String(length=500), nullable=False)
    )
    op.create_index(op.f("ix_spelltraits_name"), "spelltraits", ["name"], unique=True)
    op.add_column(
        "weaponmasterys", sa.Column("name", sa.String(length=500), nullable=False)
    )
    op.create_index(
        op.f("ix_weaponmasterys_name"), "weaponmasterys", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weaponmasterys_name"), table_name="weaponmasterys")
    op.drop_column("weaponmasterys", "name")
    op.drop_index(op.f("ix_spelltraits_name"), table_name="spelltraits")
    op.drop_column("spelltraits", "name")
    op.drop_index(op.f("ix_spelltraditions_name"), table_name="spelltraditions")
    op.drop_column("spelltraditions", "name")
    op.drop_index(op.f("ix_spellschools_name"), table_name="spellschools")
    op.drop_column("spellschools", "name")
    op.drop_index(op.f("ix_spellcomponents_name"), table_name="spellcomponents")
    op.drop_column("spellcomponents", "name")
    op.drop_index(op.f("ix_skillss_name"), table_name="skillss")
    op.drop_column("skillss", "name")
    op.drop_index(op.f("ix_feattraits_name"), table_name="feattraits")
    op.drop_column("feattraits", "name")
    # ### end Alembic commands ###
