"""initial

Revision ID: 28b8bc4a4ce9
Revises: 
Create Date: 2024-06-18 13:00:50.921580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28b8bc4a4ce9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actions_name"), "actions", ["name"], unique=True)
    op.create_table(
        "damagetypes",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_damagetypes_name"), "damagetypes", ["name"], unique=True)
    op.create_table(
        "domains",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domains_name"), "domains", ["name"], unique=True)
    op.create_table(
        "feattraits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feattraits_name"), "feattraits", ["name"], unique=True)
    op.create_table(
        "gods",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("edict", sa.String(length=300), nullable=False),
        sa.Column("anathema", sa.String(length=300), nullable=False),
        sa.Column("areas_of_interest", sa.String(length=300), nullable=False),
        sa.Column("temples", sa.String(length=300), nullable=False),
        sa.Column("worship", sa.String(length=300), nullable=False),
        sa.Column("sacred_animal", sa.String(length=300), nullable=False),
        sa.Column("sacred_color", sa.String(length=300), nullable=False),
        sa.Column("chosen_weapon", sa.String(length=300), nullable=False),
        sa.Column("taro", sa.String(length=300), nullable=False),
        sa.Column("alignment", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gods_name"), "gods", ["name"], unique=True)
    op.create_table(
        "prerequisites",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prerequisites_name"), "prerequisites", ["name"], unique=True
    )
    op.create_table(
        "races",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "requirementss",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirementss_name"), "requirementss", ["name"], unique=True
    )
    op.create_table(
        "skillss",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skillss_name"), "skillss", ["name"], unique=True)
    op.create_table(
        "spellcasts",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spellcasts_name"), "spellcasts", ["name"], unique=True)
    op.create_table(
        "spellcomponents",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spellcomponents_name"), "spellcomponents", ["name"], unique=True
    )
    op.create_table(
        "spellschools",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spellschools_name"), "spellschools", ["name"], unique=True)
    op.create_table(
        "spelltraditions",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spelltraditions_name"), "spelltraditions", ["name"], unique=True
    )
    op.create_table(
        "spelltraits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spelltraits_name"), "spelltraits", ["name"], unique=True)
    op.create_table(
        "titles",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_titles_name"), "titles", ["name"], unique=True)
    op.create_table(
        "triggers",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_triggers_name"), "triggers", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "weaponmasterys",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weaponmasterys_name"), "weaponmasterys", ["name"], unique=True
    )
    op.create_table(
        "characterclasss",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "health_by_level",
            sa.Enum("SIX", "EIGHT", "TEN", "TWELVE", name="healthbylevel"),
            nullable=False,
        ),
        sa.Column(
            "perception_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "fortitude_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "reflex_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "will_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "unarmed_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "light_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "medium_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "heavy_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column("spell_tradition_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spell_tradition_id"],
            ["spelltraditions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "characters",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "god_domain",
        sa.Column("god_id", sa.Integer(), nullable=False),
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["god_id"],
            ["gods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("god_id", "domain_id", name="idx_unique_god_domain"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("god_domain")
    op.drop_table("characters")
    op.drop_table("characterclasss")
    op.drop_index(op.f("ix_weaponmasterys_name"), table_name="weaponmasterys")
    op.drop_table("weaponmasterys")
    op.drop_table("users")
    op.drop_index(op.f("ix_triggers_name"), table_name="triggers")
    op.drop_table("triggers")
    op.drop_index(op.f("ix_titles_name"), table_name="titles")
    op.drop_table("titles")
    op.drop_index(op.f("ix_spelltraits_name"), table_name="spelltraits")
    op.drop_table("spelltraits")
    op.drop_index(op.f("ix_spelltraditions_name"), table_name="spelltraditions")
    op.drop_table("spelltraditions")
    op.drop_index(op.f("ix_spellschools_name"), table_name="spellschools")
    op.drop_table("spellschools")
    op.drop_index(op.f("ix_spellcomponents_name"), table_name="spellcomponents")
    op.drop_table("spellcomponents")
    op.drop_index(op.f("ix_spellcasts_name"), table_name="spellcasts")
    op.drop_table("spellcasts")
    op.drop_index(op.f("ix_skillss_name"), table_name="skillss")
    op.drop_table("skillss")
    op.drop_index(op.f("ix_requirementss_name"), table_name="requirementss")
    op.drop_table("requirementss")
    op.drop_table("races")
    op.drop_index(op.f("ix_prerequisites_name"), table_name="prerequisites")
    op.drop_table("prerequisites")
    op.drop_index(op.f("ix_gods_name"), table_name="gods")
    op.drop_table("gods")
    op.drop_index(op.f("ix_feattraits_name"), table_name="feattraits")
    op.drop_table("feattraits")
    op.drop_index(op.f("ix_domains_name"), table_name="domains")
    op.drop_table("domains")
    op.drop_index(op.f("ix_damagetypes_name"), table_name="damagetypes")
    op.drop_table("damagetypes")
    op.drop_index(op.f("ix_actions_name"), table_name="actions")
    op.drop_table("actions")
    # ### end Alembic commands ###
