"""updated weapon model

Revision ID: 2d979223a904
Revises: febd72014ea9
Create Date: 2024-06-26 19:29:34.922929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d979223a904"
down_revision: Union[str, None] = "febd72014ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weapon_groups",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weapon_groups_name"), "weapon_groups", ["name"], unique=True
    )
    op.create_table(
        "weapon_specializations",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weapon_specializations_name"),
        "weapon_specializations",
        ["name"],
        unique=True,
    )
    op.drop_index("ix_weaponspecializations_name", table_name="weaponspecializations")
    op.drop_table("weaponspecializations")
    op.drop_index("ix_weapongroups_name", table_name="weapongroups")
    op.drop_table("weapongroups")
    op.add_column("weapons", sa.Column("weapon_group_id", sa.Integer(), nullable=True))
    op.add_column(
        "weapons", sa.Column("weapon_specialization_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "weapons", "weapon_specializations", ["weapon_specialization_id"], ["id"]
    )
    op.create_foreign_key(None, "weapons", "weapon_groups", ["weapon_group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weapons", type_="foreignkey")
    op.drop_constraint(None, "weapons", type_="foreignkey")
    op.drop_column("weapons", "weapon_specialization_id")
    op.drop_column("weapons", "weapon_group_id")
    op.create_table(
        "weapongroups",
        sa.Column("name", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="weapongroups_pkey"),
    )
    op.create_index("ix_weapongroups_name", "weapongroups", ["name"], unique=True)
    op.create_table(
        "weaponspecializations",
        sa.Column("name", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="weaponspecializations_pkey"),
    )
    op.create_index(
        "ix_weaponspecializations_name", "weaponspecializations", ["name"], unique=True
    )
    op.drop_index(
        op.f("ix_weapon_specializations_name"), table_name="weapon_specializations"
    )
    op.drop_table("weapon_specializations")
    op.drop_index(op.f("ix_weapon_groups_name"), table_name="weapon_groups")
    op.drop_table("weapon_groups")
    # ### end Alembic commands ###
