"""changed race_id in RaceMixin

Revision ID: 3e9243edeb6f
Revises: 4a456a1ef3dc
Create Date: 2024-06-12 20:20:45.283177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e9243edeb6f"
down_revision: Union[str, None] = "4a456a1ef3dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_domains_name", table_name="domains")
    op.create_index(op.f("ix_domains_name"), "domains", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_domains_name"), table_name="domains")
    op.create_index("ix_domains_name", "domains", ["name"], unique=False)
    # ### end Alembic commands ###
