"""changed len name in general models

Revision ID: 475938973b0e
Revises: 496ac1ecf4cc
Create Date: 2024-06-17 16:03:55.791831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "475938973b0e"
down_revision: Union[str, None] = "496ac1ecf4cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "actions",
        "name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "damagetypes",
        "name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "feattraits",
        "description",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "prerequisites",
        "name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "requirementss",
        "name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "skillss",
        "description",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "titles",
        "name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "triggers",
        "name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "weaponmasterys",
        "description",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "weaponmasterys",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "triggers",
        "name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "titles",
        "name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "skillss",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "requirementss",
        "name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "prerequisites",
        "name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "feattraits",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "damagetypes",
        "name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "actions",
        "name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
