"""changed len name in general models

Revision ID: 496ac1ecf4cc
Revises: d77aa8f69b6c
Create Date: 2024-06-17 16:02:06.546736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "496ac1ecf4cc"
down_revision: Union[str, None] = "d77aa8f69b6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "actions",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "damagetypes",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "prerequisites",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "requirementss",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "titles",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.drop_constraint("titles_name_key", "titles", type_="unique")
    op.create_index(op.f("ix_titles_name"), "titles", ["name"], unique=True)
    op.alter_column(
        "triggers",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "triggers",
        "name",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_titles_name"), table_name="titles")
    op.create_unique_constraint("titles_name_key", "titles", ["name"])
    op.alter_column(
        "titles",
        "name",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "requirementss",
        "name",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "prerequisites",
        "name",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "damagetypes",
        "name",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "actions",
        "name",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
