"""added weapon mastery for character

Revision ID: 49db8c33b18f
Revises: 79e7b4b616b9
Create Date: 2024-06-28 13:31:13.764822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49db8c33b18f"
down_revision: Union[str, None] = "79e7b4b616b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_weapon_masteries",
        sa.Column(
            "mastery_level",
            postgresql.ENUM(
                "ABSENT",
                "TRAIN",
                "EXPERT",
                "MASTER",
                "LEGEND",
                name="masterylevels",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("weapon_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["weapon_id"], ["weapons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_weapon_masteries")
    # ### end Alembic commands ###
