"""added unique for God

Revision ID: 4a456a1ef3dc
Revises: 86ec64989029
Create Date: 2024-06-12 20:14:39.100680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a456a1ef3dc"
down_revision: Union[str, None] = "86ec64989029"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gods_name", table_name="gods")
    op.create_index(op.f("ix_gods_name"), "gods", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gods_name"), table_name="gods")
    op.create_index("ix_gods_name", "gods", ["name"], unique=False)
    # ### end Alembic commands ###
