"""added mixins for user and race

Revision ID: 4eca7ec89600
Revises: d4e80a5c40f5
Create Date: 2024-06-12 10:58:58.563466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4eca7ec89600"
down_revision: Union[str, None] = "d4e80a5c40f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
