"""added unique for character stats

Revision ID: 4f033ab66045
Revises: 204395aacd0e
Create Date: 2024-07-28 14:43:23.752161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f033ab66045"
down_revision: Union[str, None] = "204395aacd0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "character_stats", ["character_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "character_stats", type_="unique")
    # ### end Alembic commands ###
