"""added character point and secondary stat models

Revision ID: 5b5c87590a56
Revises: 1b26b5589447
Create Date: 2024-06-28 13:12:53.013115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b5c87590a56"
down_revision: Union[str, None] = "1b26b5589447"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_points",
        sa.Column("strength", sa.SmallInteger(), nullable=False),
        sa.Column("dexterity", sa.SmallInteger(), nullable=False),
        sa.Column("constitution", sa.SmallInteger(), nullable=False),
        sa.Column("intelligence", sa.SmallInteger(), nullable=False),
        sa.Column("wisdom", sa.SmallInteger(), nullable=False),
        sa.Column("charisma", sa.SmallInteger(), nullable=False),
        sa.Column("free", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "secondary_stats",
        sa.Column("perception", sa.SmallInteger(), nullable=False),
        sa.Column("armor_class", sa.SmallInteger(), nullable=False),
        sa.Column("attack_class", sa.SmallInteger(), nullable=False),
        sa.Column("damage_bonus", sa.SmallInteger(), nullable=False),
        sa.Column("max_health", sa.SmallInteger(), nullable=False),
        sa.Column("health", sa.SmallInteger(), nullable=False),
        sa.Column("initiative", sa.SmallInteger(), nullable=False),
        sa.Column("fortitude_saving", sa.SmallInteger(), nullable=False),
        sa.Column("reflex_saving", sa.SmallInteger(), nullable=False),
        sa.Column("will_saving", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secondary_stats")
    op.drop_table("character_points")
    # ### end Alembic commands ###
