"""added armor models

Revision ID: 66391c4edda8
Revises: 6a59cfae65ca
Create Date: 2024-06-26 16:10:27.553233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66391c4edda8"
down_revision: Union[str, None] = "6a59cfae65ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "armor_groups",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("hardness", sa.SmallInteger(), nullable=False),
        sa.Column("health", sa.SmallInteger(), nullable=False),
        sa.Column("broken_threshold", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "armor_specializations",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_armor_specializations_name"),
        "armor_specializations",
        ["name"],
        unique=True,
    )
    op.create_table(
        "armor_traits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_armor_traits_name"), "armor_traits", ["name"], unique=True)
    op.create_table(
        "armors",
        sa.Column("armor_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("UNARMED", "LIGHT", "MEDIUM", "HEAVY", name="armorcategory"),
            nullable=False,
        ),
        sa.Column("ac_bonus", sa.SmallInteger(), nullable=False),
        sa.Column("dexterity_modifier_cap", sa.SmallInteger(), nullable=True),
        sa.Column("check_penalty", sa.Boolean(), nullable=False),
        sa.Column("speed_penalty", sa.Boolean(), nullable=False),
        sa.Column("strength", sa.SmallInteger(), nullable=True),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["armor_group_id"],
            ["armor_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "armor_specialization_association",
        sa.Column("armor_id", sa.Integer(), nullable=False),
        sa.Column("armor_specialization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["armor_id"],
            ["armors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["armor_specialization_id"],
            ["armor_specializations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "armor_id",
            "armor_specialization_id",
            name="idx_unique_armor_specialization_association",
        ),
    )
    op.create_table(
        "armor_trait_association",
        sa.Column("armor_trait_id", sa.Integer(), nullable=False),
        sa.Column("armor_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["armor_id"],
            ["armors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["armor_trait_id"],
            ["armor_traits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "armor_trait_id", "armor_id", name="idx_unique_armor_trait_association"
        ),
    )
    op.drop_index("ix_armortraits_name", table_name="armortraits")
    op.drop_table("armortraits")
    op.drop_index("ix_armorspecializations_name", table_name="armorspecializations")
    op.drop_table("armorspecializations")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "armorspecializations",
        sa.Column("name", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="armorspecializations_pkey"),
    )
    op.create_index(
        "ix_armorspecializations_name", "armorspecializations", ["name"], unique=True
    )
    op.create_table(
        "armortraits",
        sa.Column("name", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="armortraits_pkey"),
    )
    op.create_index("ix_armortraits_name", "armortraits", ["name"], unique=True)
    op.drop_table("armor_trait_association")
    op.drop_table("armor_specialization_association")
    op.drop_table("armors")
    op.drop_index(op.f("ix_armor_traits_name"), table_name="armor_traits")
    op.drop_table("armor_traits")
    op.drop_index(
        op.f("ix_armor_specializations_name"), table_name="armor_specializations"
    )
    op.drop_table("armor_specializations")
    op.drop_table("armor_groups")
    # ### end Alembic commands ###
