"""initial

Revision ID: 6a59cfae65ca
Revises: 8cd1bb531b26
Create Date: 2024-06-25 15:54:00.898088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a59cfae65ca"
down_revision: Union[str, None] = "8cd1bb531b26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worns", sa.Column("level", sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worns", "level")
    # ### end Alembic commands ###
