"""updated character models

Revision ID: 6b74ff3f77bf
Revises: 18914faf0a1f
Create Date: 2024-06-28 17:33:29.062941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b74ff3f77bf"
down_revision: Union[str, None] = "18914faf0a1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_armors",
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("armor_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["armor_id"], ["armors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "armor_id", name="idx_unique_character_armors"
        ),
    )
    op.create_table(
        "character_currencies",
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["currency_id"], ["currencies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "currency_id", name="idx_unique_character_currencies"
        ),
    )
    op.create_table(
        "character_items",
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "item_id", name="idx_unique_character_items"
        ),
    )
    op.create_table(
        "character_weapons",
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("weapon_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["weapon_id"], ["weapons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "weapon_id", name="idx_unique_character_weapons"
        ),
    )
    op.create_table(
        "character_worns",
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("worn_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["worn_id"], ["worns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "worn_id", name="idx_unique_character_worns"
        ),
    )
    op.create_table(
        "equipped_items",
        sa.Column("first_weapon_id", sa.Integer(), nullable=True),
        sa.Column("second_weapon_id", sa.Integer(), nullable=True),
        sa.Column("armor_id", sa.Integer(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["armor_id"], ["character_armors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["first_weapon_id"], ["character_weapons.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["second_weapon_id"], ["character_weapons.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "worn_equipped_association",
        sa.Column("inventory_worn_id", sa.Integer(), nullable=False),
        sa.Column("equipped_worn_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipped_worn_id"], ["equipped_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["inventory_worn_id"], ["character_worns.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inventory_worn_id", "equipped_worn_id", name="idx_unique_worn_equipped"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worn_equipped_association")
    op.drop_table("equipped_items")
    op.drop_table("character_worns")
    op.drop_table("character_weapons")
    op.drop_table("character_items")
    op.drop_table("character_currencies")
    op.drop_table("character_armors")
    # ### end Alembic commands ###
