"""added unique for name in character class model

Revision ID: 76e2bc56a868
Revises: 28b8bc4a4ce9
Create Date: 2024-06-18 13:24:17.122759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76e2bc56a868"
down_revision: Union[str, None] = "28b8bc4a4ce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "characterclasss", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "characterclasss", type_="unique")
    # ### end Alembic commands ###
