"""initial commit

Revision ID: 86c63c82d8e3
Revises: 
Create Date: 2024-06-12 15:26:23.237164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86c63c82d8e3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domains_name"), "domains", ["name"], unique=False)
    op.create_table(
        "gods",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("edict", sa.String(length=300), nullable=False),
        sa.Column("anathema", sa.String(length=300), nullable=False),
        sa.Column("areas_of_interest", sa.String(length=300), nullable=False),
        sa.Column("temples", sa.String(length=300), nullable=False),
        sa.Column("worship", sa.String(length=300), nullable=False),
        sa.Column("sacred_animal", sa.String(length=300), nullable=False),
        sa.Column("sacred_color", sa.String(length=300), nullable=False),
        sa.Column("chosen_weapon", sa.String(length=300), nullable=False),
        sa.Column("taro", sa.String(length=300), nullable=False),
        sa.Column("alignment", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gods_name"), "gods", ["name"], unique=False)
    op.create_table(
        "races",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "titles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "characters",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "god_domain",
        sa.Column("god_id", sa.Integer(), nullable=False),
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["god_id"],
            ["gods.id"],
        ),
        sa.PrimaryKeyConstraint("god_id", "domain_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("god_domain")
    op.drop_table("characters")
    op.drop_table("users")
    op.drop_table("titles")
    op.drop_table("races")
    op.drop_index(op.f("ix_gods_name"), table_name="gods")
    op.drop_table("gods")
    op.drop_index(op.f("ix_domains_name"), table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
