"""added is_superuser field for User

Revision ID: 8956c42454ad
Revises: d1107425c68d
Create Date: 2024-07-03 13:45:46.294993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8956c42454ad"
down_revision: Union[str, None] = "d1107425c68d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_access_tokens_created_at", table_name="access_tokens")
    op.drop_table("access_tokens")
    op.drop_index("ix_test_users_email", table_name="test_users")
    op.drop_table("test_users")
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    op.create_table(
        "test_users",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('test_users_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="test_users_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_test_users_email", "test_users", ["email"], unique=True)
    op.create_table(
        "access_tokens",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(length=43), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["test_users.id"],
            name="access_tokens_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name="access_tokens_pkey"),
    )
    op.create_index(
        "ix_access_tokens_created_at", "access_tokens", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
