"""initial

Revision ID: 8cd1bb531b26
Revises: 7abab89272d5
Create Date: 2024-06-25 15:50:16.788773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cd1bb531b26"
down_revision: Union[str, None] = "7abab89272d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worns", "level")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worns", sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
