"""changed race to race_id

Revision ID: 92e8903ba7d4
Revises: ff29a08976a5
Create Date: 2024-06-11 19:16:30.612421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92e8903ba7d4"
down_revision: Union[str, None] = "ff29a08976a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("race_id", sa.Integer(), nullable=False))
    op.drop_constraint("characters_race_fkey", "characters", type_="foreignkey")
    op.create_foreign_key(None, "characters", "races", ["race_id"], ["id"])
    op.drop_column("characters", "race")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column("race", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.create_foreign_key(
        "characters_race_fkey", "characters", "races", ["race"], ["id"]
    )
    op.drop_column("characters", "race_id")
    # ### end Alembic commands ###
