"""added god_domain_association

Revision ID: ae11d44ad50f
Revises: ba09ae6fa598
Create Date: 2024-06-12 16:37:28.632304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae11d44ad50f"
down_revision: Union[str, None] = "ba09ae6fa598"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
