"""added absent default for character model

Revision ID: b6f2f1b9d684
Revises: 9777391d9644
Create Date: 2024-06-18 12:08:15.954546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6f2f1b9d684"
down_revision: Union[str, None] = "9777391d9644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characterclasss", "perception_mastery")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characterclasss",
        sa.Column(
            "perception_mastery",
            postgresql.ENUM(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
