"""added basic spell models, added class character model

Revision ID: bc75c9e444fc
Revises: 475938973b0e
Create Date: 2024-06-18 11:39:10.879190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc75c9e444fc"
down_revision: Union[str, None] = "475938973b0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spellcasts",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spellcasts_name"), "spellcasts", ["name"], unique=True)
    op.create_table(
        "spellcomponents",
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spellschools",
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spelltraditions",
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spelltraits",
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "characterclasss",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("health_by_level", sa.Integer(), nullable=False),
        sa.Column(
            "perception_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "fortitude_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "reflex_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "will_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "unarmed_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "light_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "medium_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "heavy_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column("spell_tradition_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spell_tradition_id"],
            ["spelltraditions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("characterclasss")
    op.drop_table("spelltraits")
    op.drop_table("spelltraditions")
    op.drop_table("spellschools")
    op.drop_table("spellcomponents")
    op.drop_index(op.f("ix_spellcasts_name"), table_name="spellcasts")
    op.drop_table("spellcasts")
    # ### end Alembic commands ###
