"""updated character model

Revision ID: c44a9d1dc700
Revises: ed862687314d
Create Date: 2024-06-27 16:28:31.866465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c44a9d1dc700"
down_revision: Union[str, None] = "ed862687314d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("size", sa.SmallInteger(), nullable=True))
    op.add_column(
        "characters", sa.Column("character_class_id", sa.Integer(), nullable=False)
    )
    op.add_column("characters", sa.Column("god_id", sa.Integer(), nullable=False))
    op.add_column("characters", sa.Column("domain_id", sa.Integer(), nullable=True))
    op.alter_column(
        "characters", "last_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "characters", "alias", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "characters",
        "age",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        nullable=True,
    )
    op.alter_column(
        "characters",
        "level",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=False,
    )
    op.alter_column("characters", "description", existing_type=sa.TEXT(), nullable=True)
    op.drop_constraint("characters_race_id_fkey", "characters", type_="foreignkey")
    op.drop_constraint("characters_user_id_fkey", "characters", type_="foreignkey")
    op.create_foreign_key(
        None, "characters", "gods", ["god_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "characters", "domains", ["domain_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "characters", "races", ["race_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "characters", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "characters",
        "character_classes",
        ["character_class_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.create_foreign_key(
        "characters_user_id_fkey", "characters", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "characters_race_id_fkey", "characters", "races", ["race_id"], ["id"]
    )
    op.alter_column("characters", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "characters",
        "level",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "characters",
        "age",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "characters", "alias", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "characters", "last_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("characters", "domain_id")
    op.drop_column("characters", "god_id")
    op.drop_column("characters", "character_class_id")
    op.drop_column("characters", "size")
    # ### end Alembic commands ###
