"""added nullable field for character class model

Revision ID: c467d8197c60
Revises: b6f2f1b9d684
Create Date: 2024-06-18 12:09:36.418451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c467d8197c60"
down_revision: Union[str, None] = "b6f2f1b9d684"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characterclasss",
        sa.Column(
            "perception_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characterclasss", "perception_mastery")
    # ### end Alembic commands ###
