"""fixed changes

Revision ID: c48ace82c5a0
Revises: 91f40355a39a
Create Date: 2024-07-02 14:55:16.548720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c48ace82c5a0"
down_revision: Union[str, None] = "91f40355a39a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worn_equipped_association",
        sa.Column("character_worn_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "idx_unique_worn_equipped", "worn_equipped_association", type_="unique"
    )
    op.create_unique_constraint(
        "idx_unique_worn_equipped",
        "worn_equipped_association",
        ["character_worn_id", "equipped_worn_id"],
    )
    op.drop_constraint(
        "worn_equipped_association_inventory_worn_id_fkey",
        "worn_equipped_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "worn_equipped_association",
        "character_worns",
        ["character_worn_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("worn_equipped_association", "inventory_worn_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worn_equipped_association",
        sa.Column(
            "inventory_worn_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "worn_equipped_association", type_="foreignkey")
    op.create_foreign_key(
        "worn_equipped_association_inventory_worn_id_fkey",
        "worn_equipped_association",
        "character_worns",
        ["inventory_worn_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "idx_unique_worn_equipped", "worn_equipped_association", type_="unique"
    )
    op.create_unique_constraint(
        "idx_unique_worn_equipped",
        "worn_equipped_association",
        ["inventory_worn_id", "equipped_worn_id"],
    )
    op.drop_column("worn_equipped_association", "character_worn_id")
    # ### end Alembic commands ###
