"""added spell model

Revision ID: c67dcb099473
Revises: f6a2ab086c11
Create Date: 2024-06-27 13:14:47.586035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c67dcb099473"
down_revision: Union[str, None] = "f6a2ab086c11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spells",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("spell_range", sa.SmallInteger(), nullable=False),
        sa.Column("duration", sa.String(length=200), nullable=False),
        sa.Column("sustain", sa.Boolean(), nullable=False),
        sa.Column("ritual", sa.Boolean(), nullable=False),
        sa.Column("secondary_casters", sa.String(length=200), nullable=True),
        sa.Column("cost", sa.String(length=200), nullable=True),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("spell_tradition_id", sa.Integer(), nullable=False),
        sa.Column("spell_component_id", sa.Integer(), nullable=True),
        sa.Column("spell_cast_id", sa.Integer(), nullable=False),
        sa.Column("spell_school_id", sa.Integer(), nullable=False),
        sa.Column("spell_trait_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spell_cast_id"], ["spell_casts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["spell_component_id"], ["spell_components.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["spell_school_id"], ["spell_schools.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["spell_tradition_id"], ["spell_traditions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["spell_trait_id"], ["spell_traits.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spells")
    # ### end Alembic commands ###
