"""added worn models

Revision ID: d0216d9be242
Revises: 2a59c508f7de
Create Date: 2024-06-18 18:06:43.995974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0216d9be242"
down_revision: Union[str, None] = "2a59c508f7de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "armorspecializations",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_armorspecializations_name"),
        "armorspecializations",
        ["name"],
        unique=True,
    )
    op.create_table(
        "armortraits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_armortraits_name"), "armortraits", ["name"], unique=True)
    op.create_table(
        "slots",
        sa.Column("slot", sa.String(length=100), nullable=False),
        sa.Column("limit", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slot"),
    )
    op.create_table(
        "weapongroups",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weapongroups_name"), "weapongroups", ["name"], unique=True)
    op.create_table(
        "weaponspecializations",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weaponspecializations_name"),
        "weaponspecializations",
        ["name"],
        unique=True,
    )
    op.create_table(
        "weapontraits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weapontraits_name"), "weapontraits", ["name"], unique=True)
    op.create_table(
        "worn_traits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_worn_traits_name"), "worn_traits", ["name"], unique=True)
    op.create_table(
        "worns",
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("activate", sa.String(), nullable=False),
        sa.Column("effect", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["slots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "worn_item_trait",
        sa.Column("worn_id", sa.Integer(), nullable=False),
        sa.Column("worn_trait_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worn_id"],
            ["worns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worn_trait_id"],
            ["worn_traits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "worn_id", "worn_trait_id", name="idx_unique_worn_item_trait"
        ),
    )
    op.drop_table("items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "weight",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("currency_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_id"], ["currencies.id"], name="items_currency_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="items_pkey"),
        sa.UniqueConstraint("name", name="items_name_key"),
    )
    op.drop_table("worn_item_trait")
    op.drop_table("worns")
    op.drop_index(op.f("ix_worn_traits_name"), table_name="worn_traits")
    op.drop_table("worn_traits")
    op.drop_index(op.f("ix_weapontraits_name"), table_name="weapontraits")
    op.drop_table("weapontraits")
    op.drop_index(
        op.f("ix_weaponspecializations_name"), table_name="weaponspecializations"
    )
    op.drop_table("weaponspecializations")
    op.drop_index(op.f("ix_weapongroups_name"), table_name="weapongroups")
    op.drop_table("weapongroups")
    op.drop_table("slots")
    op.drop_index(op.f("ix_armortraits_name"), table_name="armortraits")
    op.drop_table("armortraits")
    op.drop_index(
        op.f("ix_armorspecializations_name"), table_name="armorspecializations"
    )
    op.drop_table("armorspecializations")
    # ### end Alembic commands ###
