"""changed id

Revision ID: d1107425c68d
Revises: ae24d211d7b0
Create Date: 2024-07-02 19:09:40.573482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1107425c68d"
down_revision: Union[str, None] = "ae24d211d7b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("access_tokens", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "access_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
