"""Added column user to character model

Revision ID: d4e80a5c40f5
Revises: 92e8903ba7d4
Create Date: 2024-06-11 23:15:01.592284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4e80a5c40f5"
down_revision: Union[str, None] = "92e8903ba7d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "characters", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_column("characters", "user_id")
    # ### end Alembic commands ###
