"""added abstract and general models

Revision ID: d77aa8f69b6c
Revises: 005368013bbc
Create Date: 2024-06-17 13:36:05.245788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d77aa8f69b6c"
down_revision: Union[str, None] = "005368013bbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actions_name"), "actions", ["name"], unique=True)
    op.create_table(
        "damagetypes",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_damagetypes_name"), "damagetypes", ["name"], unique=True)
    op.create_table(
        "feattraits",
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prerequisites",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prerequisites_name"), "prerequisites", ["name"], unique=True
    )
    op.create_table(
        "requirementss",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirementss_name"), "requirementss", ["name"], unique=True
    )
    op.create_table(
        "skillss",
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "triggers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_triggers_name"), "triggers", ["name"], unique=True)
    op.create_table(
        "weaponmasterys",
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weaponmasterys")
    op.drop_index(op.f("ix_triggers_name"), table_name="triggers")
    op.drop_table("triggers")
    op.drop_table("skillss")
    op.drop_index(op.f("ix_requirementss_name"), table_name="requirementss")
    op.drop_table("requirementss")
    op.drop_index(op.f("ix_prerequisites_name"), table_name="prerequisites")
    op.drop_table("prerequisites")
    op.drop_table("feattraits")
    op.drop_index(op.f("ix_damagetypes_name"), table_name="damagetypes")
    op.drop_table("damagetypes")
    op.drop_index(op.f("ix_actions_name"), table_name="actions")
    op.drop_table("actions")
    # ### end Alembic commands ###
