"""added unique for character models

Revision ID: d8c63bffff43
Revises: 4f033ab66045
Create Date: 2024-07-28 14:55:17.951508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8c63bffff43"
down_revision: Union[str, None] = "4f033ab66045"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "character_points", ["character_id"])
    op.create_unique_constraint(None, "character_skill_masteries", ["character_id"])
    op.create_unique_constraint(None, "character_skill_masteries", ["skill_id"])
    op.create_unique_constraint(None, "character_weapon_masteries", ["weapon_id"])
    op.create_unique_constraint(None, "character_weapon_masteries", ["character_id"])
    op.create_unique_constraint(None, "secondary_stats", ["character_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "secondary_stats", type_="unique")
    op.drop_constraint(None, "character_weapon_masteries", type_="unique")
    op.drop_constraint(None, "character_weapon_masteries", type_="unique")
    op.drop_constraint(None, "character_skill_masteries", type_="unique")
    op.drop_constraint(None, "character_skill_masteries", type_="unique")
    op.drop_constraint(None, "character_points", type_="unique")
    # ### end Alembic commands ###
