"""added nullable field for character class model

Revision ID: e9bb4e38cfb3
Revises: 114d7c2c5daf
Create Date: 2024-06-18 11:58:07.851498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9bb4e38cfb3"
down_revision: Union[str, None] = "114d7c2c5daf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
