"""initial

Revision ID: ea6e07632201
Revises: 
Create Date: 2024-06-25 14:39:24.330358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea6e07632201"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actions_name"), "actions", ["name"], unique=True)
    op.create_table(
        "armorspecializations",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_armorspecializations_name"),
        "armorspecializations",
        ["name"],
        unique=True,
    )
    op.create_table(
        "armortraits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_armortraits_name"), "armortraits", ["name"], unique=True)
    op.create_table(
        "currencies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "damagetypes",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_damagetypes_name"), "damagetypes", ["name"], unique=True)
    op.create_table(
        "domains",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domains_name"), "domains", ["name"], unique=True)
    op.create_table(
        "feat_traits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feat_traits_name"), "feat_traits", ["name"], unique=True)
    op.create_table(
        "gods",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("edict", sa.String(length=300), nullable=False),
        sa.Column("anathema", sa.String(length=300), nullable=False),
        sa.Column("areas_of_interest", sa.String(length=300), nullable=False),
        sa.Column("temples", sa.String(length=300), nullable=False),
        sa.Column("worship", sa.String(length=300), nullable=False),
        sa.Column("sacred_animal", sa.String(length=300), nullable=False),
        sa.Column("sacred_color", sa.String(length=300), nullable=False),
        sa.Column("chosen_weapon", sa.String(length=300), nullable=False),
        sa.Column("taro", sa.String(length=300), nullable=False),
        sa.Column("alignment", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gods_name"), "gods", ["name"], unique=True)
    op.create_table(
        "prerequisites",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prerequisites_name"), "prerequisites", ["name"], unique=True
    )
    op.create_table(
        "races",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "requirements",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requirements_name"), "requirements", ["name"], unique=True)
    op.create_table(
        "skillss",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skillss_name"), "skillss", ["name"], unique=True)
    op.create_table(
        "slots",
        sa.Column("slot", sa.String(length=100), nullable=False),
        sa.Column("limit", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slot"),
    )
    op.create_table(
        "spellcasts",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spellcasts_name"), "spellcasts", ["name"], unique=True)
    op.create_table(
        "spellcomponents",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spellcomponents_name"), "spellcomponents", ["name"], unique=True
    )
    op.create_table(
        "spellschools",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spellschools_name"), "spellschools", ["name"], unique=True)
    op.create_table(
        "spelltraditions",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spelltraditions_name"), "spelltraditions", ["name"], unique=True
    )
    op.create_table(
        "spelltraits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spelltraits_name"), "spelltraits", ["name"], unique=True)
    op.create_table(
        "titles",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_titles_name"), "titles", ["name"], unique=True)
    op.create_table(
        "triggers",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_triggers_name"), "triggers", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "weapongroups",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weapongroups_name"), "weapongroups", ["name"], unique=True)
    op.create_table(
        "weaponmasterys",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weaponmasterys_name"), "weaponmasterys", ["name"], unique=True
    )
    op.create_table(
        "weaponspecializations",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weaponspecializations_name"),
        "weaponspecializations",
        ["name"],
        unique=True,
    )
    op.create_table(
        "weapontraits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weapontraits_name"), "weapontraits", ["name"], unique=True)
    op.create_table(
        "worn_traits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_worn_traits_name"), "worn_traits", ["name"], unique=True)
    op.create_table(
        "character_classes",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "health_by_level",
            sa.Enum("SIX", "EIGHT", "TEN", "TWELVE", name="healthbylevel"),
            nullable=False,
        ),
        sa.Column(
            "perception_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "fortitude_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "reflex_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "will_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "unarmed_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "light_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "medium_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column(
            "heavy_armor_mastery",
            sa.Enum(
                "ABSENT", "TRAIN", "EXPERT", "MASTER", "LEGEND", name="masterylevels"
            ),
            nullable=False,
        ),
        sa.Column("spell_tradition_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spell_tradition_id"],
            ["spelltraditions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "characters",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "god_domain",
        sa.Column("god_id", sa.Integer(), nullable=False),
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["god_id"],
            ["gods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("god_id", "domain_id", name="idx_unique_god_domain"),
    )
    op.create_table(
        "worns",
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("activate", sa.String(), nullable=False),
        sa.Column("effect", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["slots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "feats",
        sa.Column("character_class_id", sa.Integer(), nullable=True),
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("trigger_id", sa.Integer(), nullable=False),
        sa.Column("prerequisite_id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_class_id"],
            ["character_classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_id"],
            ["prerequisites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["triggers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "worn_item_trait",
        sa.Column("worn_id", sa.Integer(), nullable=False),
        sa.Column("worn_trait_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worn_id"],
            ["worns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worn_trait_id"],
            ["worn_traits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "worn_id", "worn_trait_id", name="idx_unique_worn_item_trait"
        ),
    )
    op.create_table(
        "feat_trait",
        sa.Column("feat_id", sa.Integer(), nullable=False),
        sa.Column("trait_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feat_id"],
            ["feats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trait_id"],
            ["feat_traits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feat_id", "trait_id", name="idx_unique_feat_trait"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feat_trait")
    op.drop_table("worn_item_trait")
    op.drop_table("feats")
    op.drop_table("worns")
    op.drop_table("god_domain")
    op.drop_table("characters")
    op.drop_table("character_classes")
    op.drop_index(op.f("ix_worn_traits_name"), table_name="worn_traits")
    op.drop_table("worn_traits")
    op.drop_index(op.f("ix_weapontraits_name"), table_name="weapontraits")
    op.drop_table("weapontraits")
    op.drop_index(
        op.f("ix_weaponspecializations_name"), table_name="weaponspecializations"
    )
    op.drop_table("weaponspecializations")
    op.drop_index(op.f("ix_weaponmasterys_name"), table_name="weaponmasterys")
    op.drop_table("weaponmasterys")
    op.drop_index(op.f("ix_weapongroups_name"), table_name="weapongroups")
    op.drop_table("weapongroups")
    op.drop_table("users")
    op.drop_index(op.f("ix_triggers_name"), table_name="triggers")
    op.drop_table("triggers")
    op.drop_index(op.f("ix_titles_name"), table_name="titles")
    op.drop_table("titles")
    op.drop_index(op.f("ix_spelltraits_name"), table_name="spelltraits")
    op.drop_table("spelltraits")
    op.drop_index(op.f("ix_spelltraditions_name"), table_name="spelltraditions")
    op.drop_table("spelltraditions")
    op.drop_index(op.f("ix_spellschools_name"), table_name="spellschools")
    op.drop_table("spellschools")
    op.drop_index(op.f("ix_spellcomponents_name"), table_name="spellcomponents")
    op.drop_table("spellcomponents")
    op.drop_index(op.f("ix_spellcasts_name"), table_name="spellcasts")
    op.drop_table("spellcasts")
    op.drop_table("slots")
    op.drop_index(op.f("ix_skillss_name"), table_name="skillss")
    op.drop_table("skillss")
    op.drop_index(op.f("ix_requirements_name"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_table("races")
    op.drop_index(op.f("ix_prerequisites_name"), table_name="prerequisites")
    op.drop_table("prerequisites")
    op.drop_index(op.f("ix_gods_name"), table_name="gods")
    op.drop_table("gods")
    op.drop_index(op.f("ix_feat_traits_name"), table_name="feat_traits")
    op.drop_table("feat_traits")
    op.drop_index(op.f("ix_domains_name"), table_name="domains")
    op.drop_table("domains")
    op.drop_index(op.f("ix_damagetypes_name"), table_name="damagetypes")
    op.drop_table("damagetypes")
    op.drop_table("currencies")
    op.drop_index(op.f("ix_armortraits_name"), table_name="armortraits")
    op.drop_table("armortraits")
    op.drop_index(
        op.f("ix_armorspecializations_name"), table_name="armorspecializations"
    )
    op.drop_table("armorspecializations")
    op.drop_index(op.f("ix_actions_name"), table_name="actions")
    op.drop_table("actions")
    # ### end Alembic commands ###
