"""added feature model

Revision ID: ed862687314d
Revises: ee7dbbfd3acc
Create Date: 2024-06-27 13:58:29.857905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed862687314d"
down_revision: Union[str, None] = "ee7dbbfd3acc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "features",
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("class_feat_count", sa.SmallInteger(), nullable=False),
        sa.Column("general_feat_count", sa.SmallInteger(), nullable=False),
        sa.Column("background_feat_count", sa.SmallInteger(), nullable=False),
        sa.Column("skill_count", sa.SmallInteger(), nullable=False),
        sa.Column("stats_boost", sa.SmallInteger(), nullable=False),
        sa.Column("feat_id", sa.Integer(), nullable=True),
        sa.Column("character_class_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_class_id"], ["character_classes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["feat_id"], ["feats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("features")
    # ### end Alembic commands ###
