"""test delete

Revision ID: f56fdb6f953a
Revises: 5556d2c4b09f
Create Date: 2024-06-26 17:45:04.696811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f56fdb6f953a"
down_revision: Union[str, None] = "5556d2c4b09f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "worn_item_trait_worn_id_fkey", "worn_item_trait", type_="foreignkey"
    )
    op.drop_constraint(
        "worn_item_trait_worn_trait_id_fkey", "worn_item_trait", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "worn_item_trait", "worns", ["worn_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "worn_item_trait",
        "worn_traits",
        ["worn_trait_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "worn_item_trait", type_="foreignkey")
    op.drop_constraint(None, "worn_item_trait", type_="foreignkey")
    op.create_foreign_key(
        "worn_item_trait_worn_trait_id_fkey",
        "worn_item_trait",
        "worn_traits",
        ["worn_trait_id"],
        ["id"],
    )
    op.create_foreign_key(
        "worn_item_trait_worn_id_fkey", "worn_item_trait", "worns", ["worn_id"], ["id"]
    )
    # ### end Alembic commands ###
