"""updated god_domain_association

Revision ID: f64efd405d44
Revises: ae11d44ad50f
Create Date: 2024-06-12 16:44:18.396434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f64efd405d44"
down_revision: Union[str, None] = "ae11d44ad50f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("god_domain", sa.Column("id", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "idx_unique_god_domain", "god_domain", ["god_id", "domain_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_unique_god_domain", "god_domain", type_="unique")
    op.drop_column("god_domain", "id")
    # ### end Alembic commands ###
