"""added weapon traits association

Revision ID: febd72014ea9
Revises: 02c07598d3c0
Create Date: 2024-06-26 19:21:17.764455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "febd72014ea9"
down_revision: Union[str, None] = "02c07598d3c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weapon_traits",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weapon_traits_name"), "weapon_traits", ["name"], unique=True
    )
    op.create_table(
        "weapon_trait_association",
        sa.Column("weapon_id", sa.Integer(), nullable=False),
        sa.Column("weapon_trait_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["weapon_id"], ["weapons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["weapon_trait_id"], ["weapon_traits.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "weapon_id", "weapon_trait_id", name="idx_unique_weapon_trait_association"
        ),
    )
    op.drop_index("ix_weapontraits_name", table_name="weapontraits")
    op.drop_table("weapontraits")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weapontraits",
        sa.Column("name", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="weapontraits_pkey"),
    )
    op.create_index("ix_weapontraits_name", "weapontraits", ["name"], unique=True)
    op.drop_table("weapon_trait_association")
    op.drop_index(op.f("ix_weapon_traits_name"), table_name="weapon_traits")
    op.drop_table("weapon_traits")
    # ### end Alembic commands ###
