version: '3.8'

services:
  asgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kingdom
    ports:
      - "8008:8008"
    depends_on:
      - db
    volumes:
      - ../logs/asgi_docker/:/config/logs
    restart: always
    env_file: .env_docker
    command: /start-asgi

  db:
    image: postgres:alpine
    env_file: .env_docker
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "88:88"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - asgi

volumes:
  pg_data: {}
