version: '3.8'

services:
  asgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kingdom
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../logs/asgi_docker/:/config/logs
    restart: always
    env_file: .env_docker
    command: /start-asgi

  db:
    image: postgres:alpine
    env_file: .env_docker
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pg_data: {}
