#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Starting migrations..."
python alembic upgrade head

echo "Starting the server..."
exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload